### ISSUE TITLE
Error when creating a report

### ISSUE THREAD

**Issue by cao42381** [blue-engine/best#18]
we are getting an error that reads...

AttributeError at /admin/best/report/1/
'User' object has no attribute 'instructor_set'
Request Method: GET
Request URL:    https://blueengine.herokuapp.com/admin/best/report/1/
Django Version: 1.8.3
Exception Type: AttributeError
Exception Value:  
'User' object has no attribute 'instructor_set'
Exception Location: /app/.heroku/python/lib/python2.7/site-packages/django/utils/functional.py in inner, line 227
Python Executable:  /app/.heroku/python/bin/python
Python Version: 2.7.10
Python Path:  
['/app',
 '/app/.heroku/python/bin',
 '/app/.heroku/python/lib/python2.7/site-packages/setuptools-18.1-py2.7.egg',
 '/app/.heroku/python/lib/python2.7/site-packages/pip-7.1.0-py2.7.egg',
 '/app',
 '/app/.heroku/python/lib/python27.zip',
 '/app/.heroku/python/lib/python2.7',
 '/app/.heroku/python/lib/python2.7/plat-linux2',
 '/app/.heroku/python/lib/python2.7/lib-tk',
 '/app/.heroku/python/lib/python2.7/lib-old',
 '/app/.heroku/python/lib/python2.7/lib-dynload',
 '/app/.heroku/python/lib/python2.7/site-packages']
Server time:    Mon, 28 Sep 2015 11:34:29 -0400

**Comment by tanfrank** [comment]
@cao42381 I was unable to replicate the error. You got it while just viewing the page?

**Comment by cao42381** [comment]
Log in as "testBETABLA2" with pass: blueengine and when you try to access a
report, the error appears. Is this a permissions issue?

On Wed, Sep 30, 2015 at 2:00 PM, Frank Scarfo notifications@github.com
wrote:

> @cao42381 https://github.com/cao42381 I was unable to replicate the
> error. You got it while just viewing the page?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/blue-engine/best/issues/18#issuecomment-144491937.

## 

Senior Director, Performance Management & Innovation
What we do
http://opinionator.blogs.nytimes.com/2013/05/15/a-team-approach-to-get-students-college-ready/
(NY
Times) + impact in schools http://blueengine.org/infographic.
75 Broad Street, Suite 2900, New York, NY 10004

"If the track is tough and the hill is rough, THINKING you can just ain’t
enough!"
